---
title: "geologic contacts script"
author: "Judy Malas"
date: "11/22/2021"
output: html_document
---

```{r load-packages}

library(tidyverse)
library(nortest)
library(ggpubr)
library(forcats)

```

Starting off by trying out the dataset for just the month of January
```{r read-jan-data}
january = read_csv("data/LST_at_contacts_sahara.csv")

str(january)
  
```

```{r histogram}

ggplot(january, aes(LST_01)) + 
  geom_histogram() +
  theme_classic() +
  labs(x = " January Land Surface Temperature")

```

```{r q-q-plot}

ggqqplot(january$LST_01)


```

```{r shapiro-wilk test}
shapiro.test(january$LST_01)

```

```{r lilliefors-test}

lillie.test(january$LST_01) 

```

volcanic = 2 
sedimentary = 3
```{r new-col-litho}
january = january %>% 
  mutate(litho = ifelse(glim == 2, "volcanic", "sedimentary"))
           

```

```{r subset-by-litho}

january_volc = january %>% 
  filter(litho == "volcanic")

january_volc 

january_sed  = january %>%  
  filter(litho == "sedimentary")

january_sed


```

```{r january-hist-by-litho}

ggplot(january_volc, aes(LST_01)) + 
  geom_histogram(alpha = 0.5) +
  theme_classic() +
  labs(x = " January Land Surface Temperature (Volcanic)")


ggplot(january_sed, aes(LST_01)) + 
  geom_histogram(alpha = 0.5) +
  theme_classic() +
  labs(x = " January Land Surface Temperature (Sedimentary)")

```

```{r january-lilli-tests}

lillie.test(january_volc$LST_01) 
lillie.test(january_sed$LST_01) 

```

```{r jan-wilcox.test}
wilcox.test(january$LST_01~january$litho)
wilcox.test(january_sed$LST_01, january_volc$LST_01)

```

```{r jan-kruskal-test}
kruskal.test(january$LST_01~january$litho)

```

```{r import-all-months-dataset}

full = read_csv("data/all_months_LST_at_contacts_sahara_20211122.csv")



```

```{r import-data-set-with-elevation}

elevation_data = read_csv("data/LST_at_contacts_sahara_20211124.csv")

ind = seq(1, nrow(elevation_data), by = 2)

elevation_data = elevation_data[-ind, ]

elevation_data$...1 = elevation_data$index


left_join(full_tidy, elevation_data, by = index)
 


```

```{r plot-elevation-v-altitude}




```



```{r pivot-dataset-longer}

full_pivot = pivot_longer(full, 8:19, names_to = "month", values_to = "LST")



```

```{r tidy}

full_tidy = full_pivot %>% 
  mutate(month_names = case_when(month == "LST_01" ~ "January", 
                                 month == "LST_02" ~ "February", 
                                 month == "LST_03" ~ "March", 
                                 month == "LST_04" ~ "April", 
                                 month == "LST_05" ~ "May", 
                                 month == "LST_06" ~ "June", 
                                 month == "LST_07" ~ "July", 
                                 month == "LST_08" ~ "August", 
                                 month == "LST_09" ~ "September", 
                                 month == "LST_10" ~ "October", 
                                 month == "LST_11" ~ "November", 
                                 month == "LST_12" ~ "December", 
                           TRUE ~ month))

full_tidy %>% 
  filter(month_names == "January") #sanity check

full_tidy = full_tidy %>% 
  mutate(litho = ifelse(glim == 2, "Volcanic", "Sedimentary"))

full_tidy = full_tidy %>% 
  mutate(month_names = fct_relevel(month_names, "January", 
                                   "February", 
                                   "March", 
                                   "April", 
                                   "May", 
                                   "June",
                                   "July", 
                                   "August",
                                   "September", 
                                   "October", 
                                   "November",
                                   "December"))


full_tidy$index = full_tidy$...1

```

```{r exploratory-vis-histo-by-month}

all_months = full_tidy %>% 
  ggplot(aes(LST, fill = litho)) +
  geom_histogram()+
  facet_wrap(month_names~litho, ncol = 4)+
  theme_classic()+
   labs(x = "Land Surface Temperature", y = "Count", fill = " " )

all_months

```

```{r exploratory-vist-scatter}

scatter_all_months = 
  ggplot(full_tidy, aes(month_names, LST, color = litho)) +
  geom_point(alpha= 0.5)+ 
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  labs(x = "", y = "Land Surface Temperature", color = "")

scatter_all_months


```

```{r box-plots}

ggplot(full_tidy, aes(month_names, LST, color = litho)) +
  geom_boxplot()+ 
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  labs(x = "", y = "Land Surface Temperature", color = "")+
  coord_flip()


```

```{r subset-by-month}

january = full_tidy %>% 
  filter(month_names == "January")

feburary = full_tidy %>% 
  filter(month_names == "February")


march = full_tidy %>% 
  filter(month_names == "March")

april = full_tidy %>% 
  filter(month_names == "April")

may = full_tidy %>% 
  filter(month_names == "May")

june = full_tidy %>% 
  filter(month_names == "June")

july = full_tidy %>% 
  filter(month_names == "July")

august = full_tidy %>% 
  filter(month_names == "August")

september = full_tidy %>% 
  filter(month_names == "September")

october = full_tidy %>% 
  filter(month_names == "October")

november = full_tidy %>% 
  filter(month_names == "November")

december = full_tidy %>% 
  filter(month_names == "December")


```

```{r wilcox-tests}

wilcox.test(january$LST~january$litho)

wilcox.test(feburary$LST~feburary$litho)

wilcox.test(march$LST~march$litho)

wilcox.test(april$LST~april$litho)

wilcox.test(may$LST~may$litho)

wilcox.test(june$LST~june$litho)

wilcox.test(july$LST~july$litho)

wilcox.test(august$LST~august$litho)

wilcox.test(september$LST~september$litho)

wilcox.test(october$LST~october$litho)

wilcox.test(november$LST~november$litho)

wilcox.test(december$LST~december$litho)

```

```{r subset-by-month-and-litho}

january_sed = full_tidy %>% 
  filter(month_names == "January", litho == "Sedimentary")

january_volc = full_tidy %>% 
  filter(month_names == "January", litho == "Volcanic")

feburary_sed = full_tidy %>% 
  filter(month_names == "February", litho == "Sedimentary")

feburary_volc = full_tidy %>% 
  filter(month_names == "February", litho =="Volcanic")

march_sed = full_tidy %>% 
 filter(month_names == "March", litho == "Sedimentary")

march_volc = full_tidy %>% 
  filter(month_names == "March", litho =="Volcanic")

april_volc = full_tidy %>% 
  filter(month_names == "April", litho =="Volcanic")

april_sed = full_tidy %>% 
  filter(month_names == "April", litho == "Sedimentary")

may_volc = full_tidy %>% 
  filter(month_names == "May", litho =="Volcanic")

may_sed = full_tidy %>% 
  filter(month_names == "May", litho == "Sedimentary")

june_volc = full_tidy %>% 
  filter(month_names == "June", litho =="Volcanic")

june_sed = full_tidy %>% 
  filter(month_names == "June", litho =="Sedimentary")

july_volc = full_tidy %>% 
  filter(month_names == "July", litho =="Volcanic")

july_sed = full_tidy %>% 
  filter(month_names == "July", litho =="Sedimentary")

august_volc = full_tidy %>% 
  filter(month_names == "August", litho =="Volcanic")

august_sed = full_tidy %>% 
  filter(month_names == "August", litho =="Sedimentary")

september_volc = full_tidy %>% 
  filter(month_names == "September", litho =="Volcanic")

september_sed = full_tidy %>% 
  filter(month_names == "September", litho =="Sedimentary")

october_volc = full_tidy %>% 
  filter(month_names == "October", litho =="Volcanic")

october_sed = full_tidy %>% 
  filter(month_names == "October", litho =="Sedimentary")

november_volc = full_tidy %>% 
  filter(month_names == "November", litho =="Volcanic")

november_sed = full_tidy %>% 
  filter(month_names == "November", litho =="Sedimentary")

december_volc = full_tidy %>% 
  filter(month_names == "December", litho =="Volcanic")

december_sed = full_tidy %>% 
  filter(month_names == "December", litho =="Sedimentary")


```

```{r make-list}

list = list(
  january_sed[,9], january_volc[,9], feburary_sed[,9], feburary_volc[,9], 
  march_sed[,9], march_volc[,9], april_volc[,9], april_sed[,9], 
  may_volc[,9], may_sed[,9], june_volc[,9], june_sed[,9], july_volc[,9], july_sed[,9], 
  august_volc[,9], august_sed[,9], september_volc[,9], september_sed[,9], 
  october_volc[,9], october_sed[,9], november_volc[,9], november_sed[,9], december_volc[,9], 
  december_sed[,9] 
)

```

```{r lillie-tests}

lillie.test(january_sed$LST)
lillie.test(january_volc$LST)

lillie.test(feburary_sed$LST)
lillie.test(feburary_volc$LST)

lillie.test(march_sed$LST)
lillie.test(march_volc$LST)


lillie.test(april_sed$LST)
lillie.test(april_volc$LST)


lillie.test(may_sed$LST)
lillie.test(may_volc$LST)

lillie.test(june_sed$LST)
lillie.test(june_volc$LST)


lillie.test(july_sed$LST)
lillie.test(july_volc$LST)

lillie.test(august_sed$LST)
lillie.test(august_volc$LST)

lillie.test(september_sed$LST)
lillie.test(september_volc$LST)

lillie.test(october_sed$LST)
lillie.test(october_volc$LST)

lillie.test(november_sed$LST)
lillie.test(november_volc$LST)

lillie.test(december_sed$LST)
lillie.test(december_volc$LST)
```

```{r qqplot}

qqdec1 = ggqqplot(december_sed$LST)
qqdec2 = ggqqplot(december_volc$LST)

ggarrange(qqdec1, qqdec2)


```

